import React from 'react'

export default function Blog14() {
    return (
        <div className="blogContainer">

            <h2>Explained: Benjamin Graham’s 7 Stock Criteria for Defensive Investors</h2>
<p>Investing in stock markets might seem overwhelming to a beginner owing to the range of options available. While stocks have the potential to deliver better returns than most investment options, it is important to choose them according to your investment plan and risk tolerance. Investments are subject to a lot of risks and returns are usually proportional to the risks associated with the investment. Today, we are going to talk about the book The Intelligent Investor by Benjamin Graham and focus on stock selection criteria for defensive investors as explained in the book.</p>
<h3>A Quick Brief About the Book – The Intelligent Investor</h3>
<p>The Intelligent Investor was first published in 1949 describing strategies to successfully use value investing strategies in the stock markets. It is referred to by investors even today and is considered to be Graham’s legacy. The book talks about a range of topics; from investment vs. speculation, the history of stock markets, enterprising and defensive investors, security analysis, etc. </p>
<p>Value investing is more popular than most other types of investing and includes the fundamental analysis of a company as opposed to its stock price or market conditions. Benjamin Graham, also known as the Father of Value Investing, was one of the early proponents of the value investing style. The book highlights various strategies to identify undervalued stocks to generate healthy returns from the investment portfolio.</p>
<h3>What are Defensive Investors</h3>
<p>According to Graham, defensive investors are investors who are unwilling to put the time and effort behind their investments. Such investors don’t prefer an active approach to invest and like a portfolio that needs minimal research and monitoring. Hence, they tend to seek conservative investments as they don’t require too much effort.</p>
<p>Most investment experts recommend investors to choose investments based on their risk tolerance levels. However, Graham believed that investors must take risks based on the amount of intelligent effort they are willing to expend.</p> 
<p>Hence, passive or defensive investors must expect average returns from their investments. Such investors can create balanced investment portfolios and invest in both equity and debt. He also recommends that conservative investors can consider investing 50% in stocks and 50% in bonds or cash. They can rebalance their portfolios when the value on either side increases by 10% or more. So, if the portfolio becomes 60% equity and 40% bonds, then defensive investors can sell 10% of their equity investments and by bonds to achieve the 50-50 balance.</p>
<p>Hence, passive or defensive investors must expect average returns from their investments. Such investors can create balanced investment portfolios and invest in both equity and debt. He also recommends that conservative investors can consider investing 50% in stocks and 50% in bonds or cash. They can rebalance their portfolios when the value on either side increases by 10% or more. So, if the portfolio becomes 60% equity and 40% bonds, then defensive investors can sell 10% of their equity investments and by bonds to achieve the 50-50 balance.</p>
<h3>Ground Rules for Stock Investing for Defensive Investors</h3>
<p>Equity investments offer the benefit of earning better returns than bonds over the long-term and protect the investor against inflation. However, these benefits can be derived only if the stocks are purchased within the right price range. For defensive investors, this is more important since they are not active and rebalance their portfolios only when some major changes occur. In the book, The Intelligent Investor, Graham offers four ground rules for defensive investors for investing in common stocks:</p>
<p> 1. Diversify Optimally – For defensive investors, diversification is an unavoidable feature of the investment portfolio. This is because defensive investors are not active investors and hence a diverse portfolio can reduce the impact of unfavorable market movement on their returns. Graham recommends that defensive investors must have between 10 and 30 stocks in their equity portfolios.</p>
<p> 2. Choose Large & Conservative Companies – Defensive investors must opt for stocks of large and conservative companies. While the returns offered by such stocks are lower than small/mid-cap companies, they are more stable and offer consistent returns. This syncs perfectly with a defensive investor’s profile. Graham recommends choosing the top 1/3 from each sector/industry.</p>
<p> 3. Look for consistent dividend payment history – Defensive investors should also look for companies that have a consistent track record of paying dividends to shareholders. Graham recommends looking at the last 20 years of dividend payment history to be sure.</p>
<p> 4. Don’t buy at any price – For defensive investors, it is important to ensure that they limit the price at which they will buy a stock. Graham recommends not paying more than 25 times the average earnings over the last 7 years and 20 times the earnings for the last 12 months. Hence, defensive investors must steer clear of growth stocks as they will be too expensive and risky for them.</p>
<h3>Graham’s 7 Stock Selection Criteria for Defensive Investors</h3>
<p>To make stock selection easy, Graham listed down 7 stock selection criteria for defensive investors. If you are a defensively-minded investor, then these criteria can help you ensure that you pick the right stock for your portfolio.</p>
<h3>Criteria 1. Size of the company</h3>
<p>Graham states that defensive investors must exclude stocks of small companies as they might be subject to more than average fluctuations. He believes that larger companies are more stable in their earnings. Also, the market sentiment towards such companies is generally optimistic. However, such companies are unlikely to surprise investors with their earnings reports. They are consistent and usually don’t under-perform or over-perform. On the other hand, if you look at a small company, the earnings can fluctuate every quarter. Graham believes that defensive investors need stocks that are less volatile. Hence, large-caps are recommended.</p>
<h3>Criteria  2. Healthy Current Ratio</h3>
<p> The Current Ratio is a popular measure of the short-term liquidity of a company. This is calculated with respect to the company’s available assets and liabilities. In simpler terms, it is a measure of the company’s ability to generate enough revenue to pay off all its debts and is often used to determine the financial health of the company. The Current Ratio is calculated as follows:</p>
<p>Current Ratio=Current Assets/Current Liabilities</p>
<h3>Criteria 3. Consistent Earnings</h3>
<p>Graham believed that for a company to be worthy of investment, it should have consistent positive earnings over time. He recommends defensive investors to look at the earnings of the past 10 years and assess if the company has been profitable and consistent overtime or not. </p>
<h3>Criteria 4. Dividend Payment History</h3>
<p>Defensive or conservative investors tend to prefer dividend-paying stocks as they usually seek a steady flow of income from their investments. Hence, they must pay attention to the dividend payment history of a company before investing in it. Graham recommends that defensive investors must look for companies that have a strong and consistent dividend payment history over the last 20 years.</p>
<h3>Criteria 5. Earnings Growth</h3>
<p>While Graham was skeptical about anyone being able to accurately predict the growth in earnings of a company, he wanted to invest in companies that are increasing their profits consistently. This was an indication that the company was heading in the right direction. He recommends defensive investors to look for companies that have experienced a minimum increase of 33% in earnings per share over the last 10 years using three-year averages at the beginning and the end.</p>
<h3>Criteria 6. Price to Earnings (P/E) Ratio</h3>
<p>Many investors look for stocks with a low price-to-earnings ratio, it cannot be the only factor to consider. According to Graham, defensive investors must look for stocks where the current market price is not more than 15 times the average earnings over the last three years. You must also remember that P/E ratios differ by sectors/industries. Hence, ensure that you look at the P/E ratios of the company’s competitors before making a decision.</p>
<h3>Criteria 7. Price to Asset Ratio</h3>
<p>The Price to Asset ratio is not used as commonly as it used to be earlier. While this is primarily due to the rise of technology companies, while analyzing companies from the traditional sectors like manufacturing, consumer staples, energy, etc., that were more capital-intensive, Price to Asset ratios can be helpful to defensive investors.</p>  

        </div>
    )
}
