import React from 'react'

export default function Blog28(){
    return(
        <div className="blogContainer">
            <h2>How are ETFs Taxed in India?</h2>

<p>Ever since their launch in India in 2002, Exchange Traded Funds or ETFs have evolved as a popular investment avenue. It is a basket of securities that usually tracks an underlying index and follows the passive investment method. The fund manager does not try to beat the market but replicate the returns offered by the index. However, before you invest in any instrument, it is important to understand the tax liability arising from income or gains generated by your investment. Today, we will talk about the taxation laws surrounding ETFs in India.</p>
<h3> Avenues to Earn Money Using ETFs</h3>
<p>Before we start looking at the taxation rules surrounding ETFs, let’s look at the different ways in which you can earn money using them.</p>

<p> An ETF or an Exchange Traded Fund is a mutual fund that follows the passive investment strategy and tracks an underlying index. It can be traded in the secondary market of a stock exchange like shares at a price determined by the demand and supply in the market. ETFs are of different categories based on the securities they invest in. These are:</p>

<ul>
<li ><span >Equity ETFs – that track a stock index and invest in equities or equity-related instruments</span></li>
<li ><span >Debt ETFs – that track bonds and invest in fixed income securities</span></li>
<li ><span >Gold ETFs – that track the actual price of gold and invest in gold</span></li>
<li ><span >International ETFs – that track stock market indices from different countries around the globe</span></li>
</ul>
<p><span>Each of these ETF types has different tax treatments. But, how do investors make money by investing in ETFs?</span></p>
<p><span >There are two to earn money using ETFs:</span></p>
<ol>
    <li ><span >Dividend Income</span></li>
    <li ><span >Capital Gains</span></li>
    </ol>

    <h4>1. Dividend Income</h4>
   <p> An ETF is a basket of securities. Hence, the dividend that you can earn by investing independently with each security will also be applicable to an ETF. For example, if you invest in an Equity ETF that has a portfolio of say 50 shares, then the fund will receive a dividend from each of those 50 companies. Some fund houses will pass on the dividends to the investors while others might reinvest the amount into the ETF and offer higher total returns. These dividends are subject to tax.</p>
    
    <h4>2. Capital Gains</h4>
   <p> Investors can trade the units of an ETF in the secondary market of a stock exchange. This market is where shares are bought and sold and the prices of shares are determined by investor sentiment and the demand and supply of a stock. Since an ETF invests in a basket of securities, the over/underperformance of one security from its basket of securities does not impact its unit price a lot. However, if the market tracked by the ETF suffers, then the price of the ETF can fall and vice versa. For example, this year, the Nifty Pharma Index that tracks the performance of some key companies in the pharmaceutical sector in India, experienced growth despite most of the other sectors failing to perform due to the pandemic. Hence, investors who had purchased an ETF that tracks the Nifty Pharma would have benefited from this movement. When you sell units of the ETF for a profit, the gains arising are defined as capital gains and taxed as per the nature of the securities held by the ETF.</p>
    
    <h3>Tax on ETFs in India</h3>
    <p>Let’s look at the taxation rules for both dividends and capital gains in India:</p>

    <h4>1. Tax on ETF Dividends </h4>
   <p> Until last year, dividend income was taxable in the hands of the company or the Mutual Fund. A dividend distribution tax or DDT of 15% was levied on all dividends paid to investors. From the financial year 2020-21, the DDT has been abolished and the dividend income is added to the annual income of the investor, and tax is deducted as per the applicable income tax slab rates. While companies and mutual funds are liable to withhold tax at the rate of 10% for dividends paid to individuals in the excess of Rs.5000, this has been relaxed to 7.5% until March 2021 considering the pandemic.</p>
    
   <p> For non-resident investors (NRIs), domestic companies and Mutual Funds are required to withhold tax at the rate of 20%. If the NRI lives in a country where the provisions of the Double Tax Avoidance Agreement (DTAA) apply, then tax computation and withholding will be done as per the restricted tax rates.</p>
    
   <h4>2. Tax on Capital Gains Made from ETFs </h4>
  <p> Since long-term and short-term capital gains are defined based on the type of securities, let’s look at the tax treatment for ETFs for each category:
    </p>
    <p><b>Tax treatment for capital gains earned from Equity ETFs</b></p>

<p>An equity ETF invests in equities or equity-related instruments. Hence, the tax treatment of capital gains made from these ETFs is similar to that of individual shares. Hence, the definitions of long-term and short-term capital gains are as follows:
</p>

<ul>
<li ><b>Long-Term Capital Gain (LTCG)</b><span > – This is any gain arising from the sale of the units of an equity exchange-traded fund that was held for </span><b>more than 12 months</b><span>.</span></li>
<li ><b>Short-Term Capital Gain (STCG)</b><span > – This is any gain arising from the sale of the units of an equity exchange-traded fund that was held for </span><b>less than 12 months</b><span>.</span></li>
</ul>
<p>The tax rates are as follows:</p>

<ul>
    <li ><span><a href="https://groww.in/p/long-term-capital-gains-tax/">LTCG</a> – Not tax for capital gains up to Rs.100000. Any LTCG in excess of Rs.1 lakh will be taxed at 10% without indexation benefits (Section 112A of the Income Tax Act, 1961)</span></li>
    <li ><span><a href="https://groww.in/p/short-term-capital-gains-tax/">STCG</a> – As per Section 111A of the Income Tax Act, 1961, STCG is taxed at 15% plus surcharge and applicable cess.</span></li>
    </ul>
    <p><b>Tax treatment for capital gains earned from Debt ETFs, Gold ETFs, and International ETFs
    </b></p>
    <p>While the tax on capital gains is different for equity investments, capital gains from debt, gold, and international ETFs are taxed in the same manner. Long-term and short-term capital gains for these ETFs are defined as follows:</p>
    <ul>
        <li ><b>Long-Term Capital Gain (LTCG)</b><span > – This is any gain arising from the sale of the units of an equity exchange-traded fund that was held for </span><b>more than 36 months</b><span>.</span></li>
        <li ><b>Short-Term Capital Gain (STCG)</b><span > – This is any gain arising from the sale of the units of an equity exchange-traded fund that was held for </span><b>less than 36 months</b><span >.</span></li>
        </ul>

        <p><span >The tax rates are as follows:</span></p>

        <ul>
            <li ><span >LTCG – Any LTCG from debt, gold, or international ETFs will be taxed at 20% with indexation benefits</span></li>
            <li ><span >STCG – Any STCG from debt, gold, or international ETFs will be added to the investors’ annual income and taxed as per the applicable income tax slab rates</span></li>
            </ul>

    <h3>Reduce Tax Liability by Setting Off Capital Losses Arising from the Sale of an ETF</h3>
        <p>When you sell units of an ETF, there can be times when you have to book losses instead of profits. These capital losses can be set-off against capital gains to reduce tax liability. However, there are certain rules surrounding it as explained below:</p>
    
        </div>
    )
}